Add text search
zotero/translation-server-old pull request #57
Opened 2018-04-12 14:35 UTC by mrtcode

This text search needs the new [CrossRef REST translator](https://github.com/zotero/translators/pull/1618) and the [updated GBV and LoC translators](https://github.com/zotero/translators/pull/1619)

2018-04-12 14:41 UTC, mrtcode commented
The result when a single item is found:
"A note on three-space Banach space ideals" -->
```
[
    {
        "key": "BWD3P9SA",
        "itemType": "journalArticle",
        "creators": [
            {
                "firstName": "Teresa",
                "lastName": "Alvarez",
                "creatorType": "author"
            },
            {
                "firstName": "Manuel",
                "lastName": "Gonzalez",
                "creatorType": "author"
            },
            {
                "firstName": "Victor M.",
                "lastName": "Onieva",
                "creatorType": "author"
            }
        ],
        "tags": [],
        "publicationTitle": "Archiv der Mathematik",
        "journalAbbreviation": "Arch. Math",
        "volume": "46",
        "issue": "2",
        "ISSN": "0003-889X",
        "date": "2/1986",
        "pages": "169-170",
        "DOI": "10.1007/bf01197495",
        "title": "A note on three-space Banach space ideals",
        "libraryCatalog": "CrossRef REST"
    }
]
```
The result when multiple items are found:
"Alice's Adventures in Wonderland" -->
```
{
    "10.1515/9781400874262-002": {
        "itemType": "bookSection",
        "title": "Alice’s Adventures in Wonderland",
        "description": "Alice’s Adventures in Wonderland (2015)  (bookSection)"
    },
    "10.1017/cbo9781139568555": {
        "itemType": "book",
        "title": "Alice's Adventures in Wonderland",
        "description": "Alice's Adventures in Wonderland (2009) Lewis Carroll, John Tenniel (book)"
    },
    "10.1515/9781400874262": {
        "itemType": "book",
        "title": "Alice's Adventures in Wonderland: Princeton University Press",
        "description": "Alice's Adventures in Wonderland: Princeton University Press (2015) Lewis Carroll (book)"
    }
}
```

2018-04-12 18:45 UTC, dstillman requested changes

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		if (identifiers.length && identifiers[0].PMID && identifiers[0].PMID !== data.trim()) {
Add comment

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +let textSearch = new function () {
We might move it elsewhere later, but for now this should go within `Zotero.Server.Translation.Search` (like, e.g., `saveWebpage` in `/web`).

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		query = query.replace(/[:]/g, ' ');
Don't need square brackets.

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +			translate.setSearch(item);
Sort of weird that we ever call this `item`, so let's just pass the object straight to `setSearch` to avoid that here.

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +				translate.translate({
Move up to same line as `await`, here and below

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		}
When can this fail? We should at least add a `Zotero.debug(e);` here and below.

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +	}
So at least as long as we're using the same order here as `priority`, we could just use the built-in translator fallback mechanism (as already used for identifiers in /search) and not hard-code translatorIDs here. That would mean having `detectSearch` actually return true for `query`, and then having the translation architecture pick the translators.

While slightly less efficient, it would mean that we could make changes to our lookup services without modifying translation-server code, and any installations would get those changes when they pulled updated translators.

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		return false;
If I'm reading this right, this seems cleaner:

```javascript
return authors.some(author => {
    return (author.firstName && this.normalize(author.firstName).includes(word))
        || (author.lastName && this.normalize(author.lastName).includes(word));
});
```

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		text = XRegExp.replace(text, rx, '');
Should document what some of this is doing.

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +			title = title.replace(/[:]/g, ' ');
Remove brackets

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		let text = item.title;
The description is meant to be displayed the title, like the green line below titles on Google Scholar. So it shouldn't include the title, and we want to present it a bit differently. I think `[first three creator last names] - [year] - [publicationTitle|publisher]` makes sense. (We can fine-tune the exact formatting later.)

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		}
We can do something fancier (mirroring the Creator column in the client) later, but should limit this to up to three creator last names for now.

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +		text += ' (' + item.itemType + ')';
No item type in the description

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +			if (maxLen) {
`if (!maxLen) continue;`

2018-04-12 18:45 UTC, dstillman commented on src/server_translation.js
> +	async function filterResults(items, query) {
Need comments throughout this function

2018-04-13 06:02 UTC, zuphilip commented
Can we then also add more information about this in the README?

2018-04-13 11:01 UTC, mrtcode commented
I am not sure how well we should document this feature, because it's for internal usage only. But we can probably add something.

2018-04-13 13:04 UTC, dstillman commented
We'll document this, but probably not until we've run it for a little while to make sure the APIs are stable and it works well enough.

2018-04-18 06:14 UTC, merged